export const CURRENT_ACCOUNT_KEY = 'currentAccountId'
export const CURRENT_REQUEST_ID = 'currentRequestId'
export const DEFAULT_USER_ID = 'unauthorized'
export const DEFAULT_REQUEST_ID = 'undefined'
export const DEFAULT_METHOD_NAME = 'unknown'
